spring:
  data:
    mongodb:
      uri: "mongodb+srv://uno-game:XZXnhfym2a6ThcHM@cluster0.72cfk.mongodb.net/uno?retryWrites=true&w=majority"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher