spring:
  profiles:
    active: local

---

spring:
  profiles: local
  data:
    mongodb:
      uri: "mongodb://localhost:27017/uno"
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

---

spring:
  profiles: prod
  data:
    mongodb:
      uri: "mongodb+srv://uno-game:KkCTJZFC16FOlSuk@cluster0.72cfk.mongodb.net/uno?retryWrites=true&w=majority"
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher