package com.uno.enums;

public enum CardSlug {
    RED_0, RED_1, RED_2, RED_3, RED_4, RED_5, RED_6, RED_7, RED_8, RED_9,
    YELLOW_0, YELLOW_1, YELLOW_2, YELLOW_3, YELLOW_4, YELLOW_5, YELLOW_6, YELLOW_7, YELLOW_8, YELLOW_9,
    BLUE_0, BLUE_1, BLUE_2, BLUE_3, BLUE_4, BLUE_5, BLUE_6, BLUE_7, BLUE_8, BLUE_9,
    GREEN_0, GREEN_1, GREEN_2, GREEN_3, GREEN_4, GREEN_5, GREEN_6, GREEN_7, GREEN_8, GREEN_9,

    RED_D2, YELLOW_D2, BLUE_D2, GREEN_D2,

    RED_REVERSE, YELLOW_REVERSE, BLUE_REVERSE, GREEN_REVERSE,

    RED_SKIP, YELLOW_SKIP, BLUE_SKIP, GREEN_SKIP,

    WILD, WILD_D4;
}
